version: '3.8'
services:
  voucher-service:
    build:
      context: ./voucher-service
      dockerfile: Dockerfile
    image: voucher-service:latest
    container_name: voucher-service
    #restart: on-failure
    ports:
      - "8081:8081"
    network_mode: "host"
    depends_on:
      - mysql
  vendor-service:
    build:
      context: ./vendor-service
      dockerfile: Dockerfile
    image: vendor-service:latest
    container_name: vendor-service
    #restart: on-failure
    ports:
      - "8082:8082"
    network_mode: "host"
  mysql:
    image: mysql:5.7
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
        - ./tmp-docker-vol/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: voucher
      MYSQL_USER: myusername
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    network_mode: "host"
  vendor-mockserver:
    image: mockserver/mockserver:mockserver-5.11.1
    container_name: vendor-mockserver
    ports:
      - "1080:1080"
    volumes:
      - ./mockserver:/config
    network_mode: "host"
    environment:
      MOCKSERVER_PROPERTY_FILE: /config/mockserver.properties
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializerJson.json

